import { inter } from "@/config/fonts";
import type { Metadata } from "next";
import Providers from "./providers";

import Header from "@/components/ui/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header />
        <main className="container mx-auto p-4 max-w-6xl">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
