// Generated by https://quicktype.io

export interface BalanceResponse {
  RESPONSE: Response;
}

export interface Response {
  MENSAJE: Mensaje;
  SALDO_F: { text: string };
  SALDO: { text: string };
}

export interface Mensaje {
  CODIGO: { text: string };
  TEXTO: { text: string };
}
