// Generated by https://quicktype.io

export interface ValidateMeResponse {
  RESPONSE: Response;
}

export interface Response {
  MENSAJE: Mensaje;
  IDENTIFYME: Identifyme;
}

export interface Identifyme {
  VALID: { text: string };
}

export interface Mensaje {
  CODIGO: { text: string };
  TEXTO: { text: string };
  NOMBRECOMERCIO: { text: string };
  DIRECCION: { text: string };
}
